# Generated by Django 2.0.5 on 2018-10-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='agent',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='guestbook',
            name='ip',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
