# Generated by Django 2.0.5 on 2019-02-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0004_auto_20190216_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='apacheii',
            name='updateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='apacheii',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
