# Generated by Django 2.0.5 on 2019-02-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0005_auto_20190219_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apacheii',
            name='scoreTime',
            field=models.DateTimeField(verbose_name='打分时间'),
        ),
    ]
