# Generated by Django 2.0.5 on 2019-02-22 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0007_qualitycontrol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitycontrol',
            name='scoreDate',
        ),
        migrations.AddField(
            model_name='qualitycontrol',
            name='qcDate',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, unique=True, verbose_name='质控日期'),
            preserve_default=False,
        ),
    ]
