# Generated by Django 2.0.5 on 2019-02-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0008_auto_20190222_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitycontrol',
            name='qcDate',
            field=models.DateField(db_index=True, verbose_name='质控日期'),
        ),
    ]
