# Generated by Django 2.0.1 on 2019-02-25 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0009_auto_20190223_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitycontrol',
            name='newAVCatheter',
        ),
        migrations.RemoveField(
            model_name='qualitycontrol',
            name='newUrethralCatheter',
        ),
        migrations.RemoveField(
            model_name='qualitycontrol',
            name='tracheaCannula',
        ),
    ]
