# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-28 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0010_auto_20190225_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apacheii',
            name='doctor',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
