# Generated by Django 2.0.5 on 2019-03-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0011_auto_20190301_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apacheii',
            name='scoreTime',
            field=models.DateTimeField(db_index=True, verbose_name='打分时间'),
        ),
    ]
