# Generated by Django 2.1 on 2019-03-11 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0019_auto_20190302_1855'),
        ('icu', '0012_auto_20190302_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilingual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.TextField()),
                ('dst', models.TextField()),
                ('bil', models.TextField()),
                ('ip', models.CharField(max_length=40)),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.User')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
