# Generated by Django 2.0.5 on 2019-03-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0014_bilingual_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilingual',
            name='doctor',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
