# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='note', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('click_time', models.IntegerField(default=1)),
                ('public', models.BooleanField(default=True)),
                ('base_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notebook.Note', verbose_name='父目录')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('passwd', models.CharField(max_length=30)),
                ('intensive_passwd', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('qq', models.IntegerField(null=True)),
                ('wechat', models.IntegerField(null=True)),
                ('phone', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.User'),
        ),
    ]
