# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0009_auto_20171128_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='basedir',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='son_notes', to='notebook.Note', verbose_name='父目录'),
        ),
    ]
