# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0010_auto_20171129_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='type',
        ),
        migrations.AddField(
            model_name='note',
            name='note_type',
            field=models.IntegerField(default=0),
        ),
    ]
