# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0012_auto_20171224_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='basedir',
        ),
        migrations.AddField(
            model_name='note',
            name='basedir_id',
            field=models.IntegerField(default=0),
        ),
    ]
