# Generated by Django 2.0.5 on 2018-10-28 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0013_auto_20180104_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-id']},
        ),
    ]
