# Generated by Django 2.0.5 on 2019-02-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0014_auto_20181028_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
