# Generated by Django 2.0.5 on 2019-03-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0015_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workmate',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
