# Generated by Django 2.0.5 on 2019-03-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0016_user_workmate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
