# Generated by Django 2.0.5 on 2019-03-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0017_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='workmate',
            field=models.CharField(default='', max_length=300),
        ),
    ]
