# Generated by Django 2.0.5 on 2019-03-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0018_auto_20190302_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(default='', max_length=45),
        ),
    ]
