# Generated by Django 2.0.5 on 2019-06-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0020_auto_20190314_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='departmentImg',
            field=models.CharField(default='', max_length=45, null=True),
        ),
    ]
