# Generated by Django 2.2.5 on 2019-09-21 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0021_user_departmentimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='Stats_lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('describe', models.TextField(blank=True, null=True)),
                ('public', models.BooleanField(default=False)),
                ('thumbs_up', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.User')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Stats_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('describe', models.TextField(blank=True, null=True)),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.Stats_lab')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Stats_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('data_type', models.IntegerField(default=1)),
                ('data_0', models.IntegerField(null=True)),
                ('data_1', models.FloatField(null=True)),
                ('data_2', models.IntegerField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.Stats_group')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
