# Generated by Django 2.2.5 on 2019-09-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0022_auto_20190921_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats_data',
            old_name='data_2',
            new_name='data_enum',
        ),
        migrations.RenameField(
            model_name='stats_data',
            old_name='data_1',
            new_name='data_float',
        ),
        migrations.RenameField(
            model_name='stats_data',
            old_name='data_0',
            new_name='data_int',
        ),
        migrations.AddField(
            model_name='stats_group',
            name='avg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stats_group',
            name='std',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stats_lab',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
