# Generated by Django 2.2.5 on 2019-10-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0023_auto_20190921_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_index=True, max_length=100)),
                ('url', models.CharField(db_index=True, max_length=100, null=True)),
                ('ip', models.CharField(max_length=40, null=True)),
                ('agent', models.CharField(max_length=100, null=True)),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='nickName',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
