# Generated by Django 2.2.5 on 2019-11-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0024_auto_20191013_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fortune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
